version: '3.8'

services:
  backend:
    build:
      context: ./Flight-Search
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - API_KEY={Insert_your_API_key}
      - API_SECRET={Insert_your_API_secret}
    networks:
      - app_network


  frontend:
    build:
      context: ./FS-BK2_II
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

